# Indepent JointTrajectoryController for arms and waist
# Position controller for gripper, hand and head

crom2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Waist controller         ------------------------------------
  waist_controller:
    type: "position_controllers/JointPositionController"
    joint: waist_joint
  
  # Head controller      ------------------------------------
  head_pan_position_controller:
    type: "position_controllers/JointPositionController"
    joint: head_pan_joint

  head_tilt_position_controller:
    type: "position_controllers/JointPositionController"
    joint: head_tilt_joint
    
  gazebo_ros_control/pid_gains:
    waist_joint: {p: 10000.0, i: 1.0, d: 1.0}
    head_pan_joint: {p: 50.0, i: 5.0, d: 10.0}
    head_tilt_joint: {p: 50.0, i: 5.0, d: 10.0}
